/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a1java;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        final int len = 10;
        final int[] arr = new int[len];
        System.out.println(new App().getGreeting());
    }
}
